wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719713008
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 23
      4: 3.11.9
      5: 0.17.3
      6: 4.41.2
      8:
      - 3
      - 5
      13: windows-amd64
